### ISSUE TITLE
name 'Submod' is not defined

### ISSUE THREAD

**Issue by pessoa1m** [Rubiksman78/MonikA.I#43] opened 2023-02-27 00:10 UTC
I am having the following problem after trying to install the mod. Would it be because I don't have NVIDIA GPU?

The version of the mod is the last one. My python version is 3.10.10.

![2023-02-27 00_01_14-MonikA I  Submod](https://user-images.githubusercontent.com/22528689/221445951-62c2e845-2707-430b-91b5-f80ce97f5452.png)
![2023-02-26 23_54_19-Configurações](https://user-images.githubusercontent.com/22528689/221445953-e80c1c58-b289-442b-a224-575982f42eda.png)
![2023-02-26 23_53_51-](https://user-images.githubusercontent.com/22528689/221445954-0da6bde1-e3d0-4e5a-a3c3-288840d30331.png)
![2023-02-27 00_04_54-AIDA64 Extreme](https://user-images.githubusercontent.com/22528689/221445955-d9832dba-7017-4565-80fd-07c3159c419d.png)

**Comment by Rubiksman78** [comment] 2023-02-27 07:40
The main issue here is that you don't seem to have the Auto Updater Submod that causes the error in Renpy because it is not recognized here. Install the Auto Updater Submod or delete the files `monikai_header.rpy` and `monikai_header.rpyc`; it can lead to unexpected behaviours and you'll have to manually install the Renpy files at each update.

I am not sure if it will work if you don't have a GPU for the most recent version as stated in #42 but it is not the issue in this case.

**Comment by Rubiksman78** [comment] 2023-04-24 04:50
I will close it for now, feel free to reopen it if needed.

**Closed by Rubiksman78** 2023-04-24 04:50 UTC
Labels: bug
